services:
  - type: web
    name: pnl-automatonsx
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATA_DIR
        value: /tmp
